### ISSUE TITLE
Improve Comments

### ISSUE THREAD

**Issue by mahowa** [mahowa/Covid-19-d3#11]
Ive left a lot of comments throughout the code. If your new to d3 this could be a good way to get started.

walk through my `LineChart/line-chart.js` and try to find the documentation to the code ive written and commented.
Add some better information there or just a link to the doc. 

I want to make this project as useful as an example of what you can do with d3 and also provide helpful information to get started

**Comment by warengonzaga** [comment]
hi @mahowa I would like to take this task... can you assign it to me?

**Comment by Anamika810** [comment]
I would like to work on this.

**Comment by mahowa** [comment]
@WarenGonzaga Ill give this one to you since you commented first

**Comment by mahowa** [comment]
@Anamika810 you can take this on after waren puts in a pr so that we are doing the same work twice

**Comment by warengonzaga** [comment]
@mahowa thanks I will work on it

**Comment by warengonzaga** [comment]
@mahowa can you assign it to me so I can secure this task for my PR?

**Comment by warengonzaga** [comment]
@mahowa by improving the comments is it necessary to add links to D3 documentation?

**Comment by mahowa** [comment]
@WarenGonzaga no that was just an example of one way to improve the comments

**Comment by warengonzaga** [comment]
Kindly review my PR @mahowa thank you! Sorry for the delay.
