### ISSUE TITLE
Add Text Data

### ISSUE THREAD

**Issue by mahowa** [mahowa/Covid-19-d3#13]
It would be nice to see some sort of table showing you simple stats

Examples:
- Total Cases
- Total Deaths
- Cases in the last week

Get creative here and make sure these stats are linked to the filters for the chart. We dont want the chart saying one thing and the text data saying something else

You dont have to style this but it sure would be nice

**Comment by simonhoyos** [comment]
Hi @mahowa, I've never worked with d3 but I would love to give this one a try if that's ok with you

**Comment by Anamika810** [comment]
I would like to work on this.

**Comment by mahowa** [comment]
hi @simonhoyos this task actually shouldn't need to know d3 just look at the data and output the text.

@Anamika810 if you want to come up with three other text fields other than the one i listed you can both work on this

**Comment by simonhoyos** [comment]
@mahowa sounds good. I'll start working on this ASAP
