### ISSUE TITLE
Animate data changes on the Line Chart

### ISSUE THREAD

**Issue by mahowa** [mahowa/Covid-19-d3#14]
Do this using transition. here is some docs on how to do it http://duspviz.mit.edu/d3-workshop/transitions-animation/

**Comment by irina-chernik** [comment]
@mahowa Hi, may I work on this?

**Comment by github-byte** [comment]
Hi can I work on this

**Comment by mahowa** [comment]
@irina-chernik all yours!

**Comment by mahowa** [comment]
We now need to implement animation on the area fill
