### ISSUE TITLE
Make project work outside code sandbox

### ISSUE THREAD

**Issue by mahowa** [mahowa/Covid-19-d3#17]
Ive only run this in code sandbox so I didnt realize it didnt work outside it. if someone wants to fix this that would be huge to help others

**Comment by mahowa** [comment]
@irina-chernik this is yours if you want it

**Comment by mahowa** [comment]
Helpful information @irina-chernik provided https://flaviocopes.com/parcel-regeneratorruntime-not-defined/

**Comment by irina-chernik** [comment]
@mahowa Thanks, already on my way to do it)

**Comment by mahowa** [comment]
@all-contributors please add @irina-chernik to code
