### ISSUE TITLE
Add Prettier

### ISSUE THREAD

**Issue by mahowa** [mahowa/Covid-19-d3#25]
Add prettier to the project 

Hint: Use lint-staged to to add the files to the commit after running
Hint: Use husky to run this command pre commit

**Comment by aayushbisen** [comment]
Hi, can I work on this issue?

**Comment by mahowa** [comment]
@aayushbisen all yours!

**Comment by AdnCodez** [comment]
I can make this PR in the next hour can I work on it even if it is assigned? 😕
Is it okay @aayushbisen

**Comment by aayushbisen** [comment]
okay @AdnCodez

**Comment by AdnCodez** [comment]
Thanks :)
