### ISSUE TITLE
Add loading screen

### ISSUE THREAD

**Issue by mahowa** [mahowa/Covid-19-d3#26]
When data is being loaded into the window it would be nice to have a loading screen.

The more creative the better here.

**Comment by guptapranav4299** [comment]
I would like to work on it  @mahowa

**Comment by mahowa** [comment]
Great @guptapranav4299 this task is all yours

**Comment by guptapranav4299** [comment]
how to run the project @mahowa

**Comment by guptapranav4299** [comment]
??

**Comment by guptapranav4299** [comment]
Also what js framework is being used vue react ?

**Comment by 3zk1m0** [comment]
There is none, it's plain html/js with d3 library
I actually just scribbled this.
I made one with spin.js, its not the most optimal one.
So if you still interested, go for it 😉

**Comment by mahowa** [comment]
There are two ways to run this. Locally, just run `npm i` then `npm run start` (ill add this to the readme)

or open it up in codesandbox, fork it, work on your code there. Then on the left panel there is a github icon that if you click it will tell you how to open a pr
