### ISSUE TITLE
Add jest to project and write a test

### ISSUE THREAD

**Issue by mahowa** [mahowa/Covid-19-d3#3]
https://jestjs.io/

Comment here if you would like me to assign this to you

**Comment by ashish979** [comment]
I can pick this one.

**Comment by mahowa** [comment]
@ashish979 this one is yours

**Comment by warengonzaga** [comment]
@ashish979 are you still working on this?

**Comment by ashish979** [comment]
@WarenGonzaga Yes I am but I cannot complete this before tomorrow as I am busy with office work and reactsummit today. It is ok if you want to go ahead and pick this one.

**Comment by warengonzaga** [comment]
@ashish979 let me know if you can complete this tomorrow then assign it to me if possible. I respect you ;)

**Comment by ashish979** [comment]
@mahowa Assign this to the amazing @WarenGonzaga. Thanks :)

**Comment by warengonzaga** [comment]
Alright thank you @ashish979!

**Comment by ashish979** [comment]
@WarenGonzaga Are you done with this or need some help?

**Comment by warengonzaga** [comment]
@ashish979 you can take it now...

**Comment by ashish979** [comment]
Hi @mahowa 
Raised PR https://github.com/mahowa/Covid-19-d3/pull/46 for this issue.
I have written tests for data.js for now. Once this PR is merged, I will add more tests.

**Comment by mahowa** [comment]
Once the conflicts are fixed @ashish979 i will merge
