### ISSUE TITLE
Add a date range selector

### ISSUE THREAD

**Issue by mahowa** [mahowa/Covid-19-d3#4]
Here is are some examples but let your imaginations go wild 

- https://codepen.io/cmessinides/pen/LvYPdp
- http://square.github.io/crossfilter/.  (this is more of what were looking for but either works)

**Comment by PradeepNalluri** [comment]
Hi, @mahowa I am interested to work on this if that's okay with you. Just wanna mention that I am a beginner in js and this will be a great learning opportunity.
Thanks
PN

**Comment by irina-chernik** [comment]
Hi @mahowa, can I take this issue?
