### ISSUE TITLE
Fix bad data

### ISSUE THREAD

**Issue by mahowa** [mahowa/Covid-19-d3#50]
Some of the data reported by the New York Times is incorrect. 

The issue im seeing specifically is some states are reporting negative data (clearly incorrect)

lets set the min of all the data to 0

heres an example
![Screen Shot 2020-10-20 at 10 40 09 AM](https://user-images.githubusercontent.com/8989577/96617477-e8948380-12c0-11eb-89ff-d39af83a23c1.png)

**Comment by cardinalion** [comment]
Can I take this issue?

**Comment by mahowa** [comment]
all yours @cardinalion
