### ISSUE TITLE
Format Text Data

### ISSUE THREAD

**Issue by mahowa** [mahowa/Covid-19-d3#62]
The text data is hard to read lets make it look cleaner

EDIT: How about we shorten the text so that instead of 10123 its says 10.1K. Then if you hover over it a little title over the number can say the exact number. make the numbers easily digestible.

2500000 -> 2.5M

**Comment by tusharck** [comment]
I can take this issue, can you assign me?

**Comment by firsi** [comment]
Hey @mahowa , can you tell me more about you want?

**Comment by RuteshRathod** [comment]
Hey @mahowa could you be more specific ?

**Comment by KarthiK2601** [comment]
can you assign me this

**Comment by mahowa** [comment]
How about we shorten the text so that instead of 10123 its says 10K. Then if you hover over it a little title over the number can say the exact number. make the numbers easily digestible.

**Comment by sandeep-v1404** [comment]
Hello @mahowa . I am interested in completing this task . Can you assign me this Issue ?

Thanks..

**Comment by lenadgit** [comment]
could you please provide more details?
