### ISSUE TITLE
Issue while raising pull request

### ISSUE THREAD

**Issue by Deepi1219** [mahowa/Covid-19-d3#77]
### Description
GitHub Workflows(greetings and test) are failing on new pull requests

### Steps to reproduce:
1. Raise a new pull request

### Expected behaviour: 
Both the checks(greetings and test) should be run successfully

### Screenshot:
<img width="927" alt="Screenshot 2020-10-25 at 2 08 45 PM" src="https://user-images.githubusercontent.com/55830172/97102475-d86b1280-16cb-11eb-8ca1-f493dbdcb03b.png">

**Comment by mahowa** [comment]
Thanks ill take care of that

**Comment by mahowa** [comment]
@all-contributors please add @Deepi1219 to issues

**Comment by mahowa** [comment]
@all-contributors please add @Deepi1219 to bug
