### ISSUE TITLE
Chart Dimensions

### ISSUE THREAD

**Issue by mahowa** [mahowa/Covid-19-d3#83]
We updated the chart height to be the size of the screen. This is great because now you can see the whole chart on any screen.

This sizing isn't great for data vis though so let make one more update.

Using a 2:3 height to width ratio. Lets limit the size of the chart. 

Requirements:

1) Make sure the chart is always fully visible on the screen. Never let height or width go beyond the screen height or width.
2) Keep the chart ratio.

**Comment by amitchakraborti9** [comment]
I wanna give a shot at this.
