### ISSUE TITLE
'Show Cumulative' switch is not working

### ISSUE THREAD

**Issue by Deepi1219** [mahowa/Covid-19-d3#89]
Show cumulative toggle next to states filter is not working. 

![cumulative_issue](https://user-images.githubusercontent.com/55830172/97783129-a706b100-1bbb-11eb-9eed-679542307761.gif)

This was working when checkbox was there instead of switch.

**Comment by mahowa** [comment]
@all-contributors please add @Deepi1219 to bug

**Comment by mahowa** [comment]
Ive fixed this issue by updating the data manipulation to correctly tally cases
